const Seller = require('../models/seller');
const User = require('../models/User');
const Category = require('../models/category');
const Zipcode = require('../models/zipcode');
const Coupon = require('../models/coupons');
const { issueReferralReward } = require('../utils/referral');
const mongoose = require('mongoose')


// 1. CREATE - Register new seller
const createSeller = async (req, res) => {
    const session = await mongoose.startSession();
    session.startTransaction();
    
    try {
        const {
            user_id,
            category_ids = [],
            store_info,
            bank_details = {},
            tax_info = {},
            permissions = {},
            commission = 0.00,
            zipcodes = []
        } = req.body;
        console.log(req.body)

        // Validate required fields
        if (!user_id || !store_info || !store_info.name) {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({
                success: false,
                message: 'User ID and store name are required'
            });
        }

        // Check if user exists
        const userExists = await User.findById(user_id).session(session);
        if (!userExists) {
            await session.abortTransaction();
            session.endSession();
            return res.status(404).json({
                success: false,
                message: 'User not found'
            });
        }

        // Check if user is already a seller
        const existingSeller = await Seller.findOne({ user_id }).session(session);
        if (existingSeller) {
            await session.abortTransaction();
            session.endSession();
            return res.status(409).json({
                success: false,
                message: 'User is already registered as a seller'
            });
        }

        // Validate categories if provided
        if (category_ids.length > 0) {
            const invalidCategories = [];
            for (const catId of category_ids) {
                if (!mongoose.Types.ObjectId.isValid(catId)) {
                    invalidCategories.push(catId);
                }
            }
            
            if (invalidCategories.length > 0) {
                await session.abortTransaction();
                session.endSession();
                return res.status(400).json({
                    success: false,
                    message: `Invalid category IDs: ${invalidCategories.join(', ')}`
                });
            }

            // Check if categories exist
            const categories = await Category.find({
                _id: { $in: category_ids }
            }).session(session);
            
            if (categories.length !== category_ids.length) {
                await session.abortTransaction();
                session.endSession();
                return res.status(404).json({
                    success: false,
                    message: 'One or more categories not found'
                });
            }
        }

        // Validate zipcodes if provided
        if (zipcodes.length > 0) {
            const invalidZipcodes = [];
            for (const zipId of zipcodes) {
                if (!mongoose.Types.ObjectId.isValid(zipId)) {
                    invalidZipcodes.push(zipId);
                }
            }
            
            if (invalidZipcodes.length > 0) {
                await session.abortTransaction();
                session.endSession();
                return res.status(400).json({
                    success: false,
                    message: `Invalid zipcode IDs: ${invalidZipcodes.join(', ')}`
                });
            }

            // Check if zipcodes exist
            const zipcodesExist = await Zipcode.find({
                _id: { $in: zipcodes }
            }).session(session);
            
            if (zipcodesExist.length !== zipcodes.length) {
                await session.abortTransaction();
                session.endSession();
                return res.status(404).json({
                    success: false,
                    message: 'One or more zipcodes not found'
                });
            }
        }

        // Check if uploaded files are available
        // if (!req.uploadedFiles || !req.uploadedFiles.national_identity_card) {
        //     await session.abortTransaction();
        //     session.endSession();
        //     return res.status(400).json({
        //         success: false,
        //         message: 'National identity card is required'
        //     });
        // }

        // Create seller (slug will be auto-generated by pre-save hook)
        const seller = new Seller({
            user_id,
            category_ids,
            store_info: {
                name: store_info.name.trim(),
                description: store_info.description?.trim() || '',
                logo: store_info.logo || '',
                url: store_info.url || ''
            },
            bank_details,
            // documents: {
            //     national_identity_card: req.uploadedFiles.national_identity_card?.secure_url || '',
            //     address_proof: req.uploadedFiles.address_proof?.secure_url || '',
            //     pan_number: parsedStoreInfo.pan_number || ''
            // },
            tax_info,
            permissions: {
                require_products_approval: permissions.require_products_approval !== false,
                customer_privacy: permissions.customer_privacy !== false,
                view_order_otp: permissions.view_order_otp !== false,
                assign_delivery_boy: permissions.assign_delivery_boy !== false
            },
            commission: parseFloat(commission) || 0.00,
            zipcodes,
            status: 'not_approved'
        });

        await seller.save({ session });

        await session.commitTransaction();
        session.endSession();

        // Populate references
        const populatedSeller = await Seller.findById(seller._id)
            .populate('user_id', 'username email mobile')
            .populate('category_ids', 'name slug')
            .populate('zipcodes', 'zipcode')
            .lean();

        res.status(201).json({
            success: true,
            message: 'Seller registered successfully',
            data: populatedSeller
        });

    } catch (error) {
        // Clean up uploaded files if transaction fails
        if (req.uploadedFiles) {
            await cleanupUploadedFiles(req.uploadedFiles);
        }
        await session.abortTransaction();
        session.endSession();
        
        console.error('Error creating seller:', error);
        
        if (error.name === 'ValidationError') {
            const messages = Object.values(error.errors).map(err => err.message);
            return res.status(400).json({
                success: false,
                message: 'Validation failed',
                errors: messages
            });
        }
        
        if (error.code === 11000) {
            return res.status(409).json({
                success: false,
                message: 'Slug already exists'
            });
        }
        
        res.status(500).json({
            success: false,
            message: 'Failed to register seller',
            error: NODE_ENV === 'development' ? error.message : undefined
        });
    }
};

// 2. READ - Get all sellers with filtering
const getAllSellers = async (req, res) => {
    try {
        const {
            page = 1,
            limit = 20,
            status,
            category_id,
            zipcode,
            search,
            min_rating = 0,
            max_rating = 5,
            approved_only = 'false',
            sort_by = 'createdAt',
            sort_order = 'desc'
        } = req.query;

        // Build query
        const query = {};

        // Filter by status
        if (status) {
            query.status = status;
        }

        // Filter by approval status
        if (approved_only === 'true') {
            query.status = 'approved';
        }

        // Filter by category
        if (category_id) {
            if (!mongoose.Types.ObjectId.isValid(category_id)) {
                return res.status(400).json({
                    success: false,
                    message: 'Invalid Category ID format'
                });
            }
            query.category_ids = category_id;
        }

        // Filter by zipcode
        if (zipcode) {
            const zipcodeDoc = await Zipcode.findOne({ zipcode });
            if (zipcodeDoc) {
                query.zipcodes = zipcodeDoc._id;
            }
        }

        // Filter by rating range
        query['ratings.average'] = {
            $gte: parseFloat(min_rating),
            $lte: parseFloat(max_rating)
        };

        // Search by store name or description
        if (search) {
            query.$text = { $search: search };
        }

        // Calculate pagination
        const pageNum = parseInt(page);
        const limitNum = parseInt(limit);
        const skip = (pageNum - 1) * limitNum;

        // Get total count
        const total = await Seller.countDocuments(query);

        // Determine sort
        let sort = { [sort_by]: sort_order === 'desc' ? -1 : 1 };
        
        // If searching, sort by text score
        if (search) {
            sort = { score: { $meta: 'textScore' }, ...sort };
        }

        // Build query for population
        let sellersQuery = Seller.find(query, search ? { score: { $meta: 'textScore' } } : null)
            .populate('user_id', 'username email mobile')
            .populate('category_ids', 'name')
            .populate('zipcodes', 'zipcode')
            .sort(sort)
            .skip(skip)
            .limit(limitNum);

        const sellers = await sellersQuery.lean();

        // Get statistics
        const stats = {
            total_sellers: await Seller.countDocuments(),
            approved_sellers: await Seller.countDocuments({ status: 'approved' }),
            pending_approval: await Seller.countDocuments({ status: 'not_approved' }),
            deactivated: await Seller.countDocuments({ status: 'deactive' }),
            removed: await Seller.countDocuments({ status: 'removed' })
        };

        res.status(200).json({
            success: true,
            message: 'Sellers retrieved successfully',
            data: {
                sellers: sellers.map(seller => ({
                    ...seller,
                    is_active: seller.status === 'approved' || seller.status === 'not_approved'
                })),
                statistics: stats,
                pagination: {
                    current_page: pageNum,
                    total_pages: Math.ceil(total / limitNum),
                    total_items: total,
                    items_per_page: limitNum,
                    has_next: pageNum < Math.ceil(total / limitNum),
                    has_previous: pageNum > 1
                }
            }
        });

    } catch (error) {
        console.error('Error fetching sellers:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to fetch sellers'
        });
    }
};

// 3. READ - Get seller by ID
const getSellerById = async (req, res) => {
    try {
        const { id } = req.params;

        // Validate ID
        if (!mongoose.Types.ObjectId.isValid(id)) {
            return res.status(400).json({
                success: false,
                message: 'Invalid Seller ID format'
            });
        }

        // Get seller with populated data
        const seller = await Seller.findById(id)
            .populate('user_id', 'username email mobile avatar')
            .populate('category_ids', 'name slug description')
            .populate('zipcodes', 'zipcode area city state')
            .lean();

        if (!seller) {
            return res.status(404).json({
                success: false,
                message: 'Seller not found'
            });
        }

        // Format response based on status
        const responseData = {
            ...seller,
            store_url: seller.store_info.url || `/store/${seller.slug}`,
            can_operate: seller.status === 'approved'
        };

        // Hide sensitive info if not approved
        if (seller.status !== 'approved') {
            delete responseData.bank_details;
            delete responseData.documents;
            delete responseData.tax_info;
            responseData.sensitive_info_hidden = true;
        }

        res.status(200).json({
            success: true,
            message: 'Seller retrieved successfully',
            data: responseData
        });

    } catch (error) {
        console.error('Error fetching seller:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to fetch seller'
        });
    }
};

// 4. READ - Get seller by user ID
const getSellerByUserId = async (req, res) => {
    try {
        const { user_id } = req.params;

        // Validate user ID
        if (!mongoose.Types.ObjectId.isValid(user_id)) {
            return res.status(400).json({
                success: false,
                message: 'Invalid User ID format'
            });
        }

        // Get seller
        const seller = await Seller.findOne({ user_id })
            .populate('category_ids', 'name')
            .populate('zipcodes', 'zipcode')
            .lean();

        if (!seller) {
            return res.status(404).json({
                success: false,
                message: 'No seller profile found for this user'
            });
        }

        res.status(200).json({
            success: true,
            message: 'Seller retrieved successfully',
            data: seller
        });

    } catch (error) {
        console.error('Error fetching seller by user ID:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to fetch seller'
        });
    }
};

// 5. READ - Get seller by slug (public storefront)
const getSellerBySlug = async (req, res) => {
    try {
        const { slug } = req.params;

        // Get seller (only approved sellers are publicly visible)
        const seller = await Seller.findOne({ 
            slug,
            status: 'approved'
        })
        .populate('category_ids', 'name slug')
        .populate('zipcodes', 'zipcode')
        .lean();

        if (!seller) {
            return res.status(404).json({
                success: false,
                message: 'Store not found or not approved'
            });
        }

        // Public response (hide sensitive info)
        const publicResponse = {
            _id: seller._id,
            slug: seller.slug,
            store_info: seller.store_info,
            ratings: seller.ratings,
            categories: seller.category_ids,
            serviceable_areas: seller.zipcodes,
            joined_date: seller.createdAt
        };

        res.status(200).json({
            success: true,
            message: 'Store retrieved successfully',
            data: publicResponse
        });

    } catch (error) {
        console.error('Error fetching seller by slug:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to fetch store'
        });
    }
};

// 6. UPDATE - Update seller profile
const updateSeller = async (req, res) => {
    const session = await mongoose.startSession();
    session.startTransaction();
    
    try {
        const { id } = req.params;
        const updateData = req.body;

        // Validate ID
        if (!mongoose.Types.ObjectId.isValid(id)) {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({
                success: false,
                message: 'Invalid Seller ID format'
            });
        }

        // Get seller
        const seller = await Seller.findById(id).session(session);
        if (!seller) {
            await session.abortTransaction();
            session.endSession();
            return res.status(404).json({
                success: false,
                message: 'Seller not found'
            });
        }

        // Prepare update object
        const updates = {};

        // Update store info
        if (updateData.store_info) {
            updates.store_info = {
                ...seller.store_info.toObject(),
                ...updateData.store_info
            };
            
            // Trim string fields
            if (updates.store_info.name) updates.store_info.name = updates.store_info.name.trim();
            if (updates.store_info.description) updates.store_info.description = updates.store_info.description.trim();
            
            // Slug will be auto-updated by pre-save hook if name changes
        }

        // Update categories
        if (updateData.category_ids !== undefined) {
            if (Array.isArray(updateData.category_ids)) {
                // Validate category IDs
                const invalidCategories = [];
                for (const catId of updateData.category_ids) {
                    if (!mongoose.Types.ObjectId.isValid(catId)) {
                        invalidCategories.push(catId);
                    }
                }
                
                if (invalidCategories.length > 0) {
                    await session.abortTransaction();
                    session.endSession();
                    return res.status(400).json({
                        success: false,
                        message: `Invalid category IDs: ${invalidCategories.join(', ')}`
                    });
                }

                // Check if categories exist
                const categories = await Category.find({
                    _id: { $in: updateData.category_ids }
                }).session(session);
                
                if (categories.length !== updateData.category_ids.length) {
                    await session.abortTransaction();
                    session.endSession();
                    return res.status(404).json({
                        success: false,
                        message: 'One or more categories not found'
                    });
                }
                
                updates.category_ids = updateData.category_ids;
            }
        }

        // Update zipcodes
        if (updateData.zipcodes !== undefined) {
            if (Array.isArray(updateData.zipcodes)) {
                // Validate zipcode IDs
                const invalidZipcodes = [];
                for (const zipId of updateData.zipcodes) {
                    if (!mongoose.Types.ObjectId.isValid(zipId)) {
                        invalidZipcodes.push(zipId);
                    }
                }
                
                if (invalidZipcodes.length > 0) {
                    await session.abortTransaction();
                    session.endSession();
                    return res.status(400).json({
                        success: false,
                        message: `Invalid zipcode IDs: ${invalidZipcodes.join(', ')}`
                    });
                }

                // Check if zipcodes exist
                const zipcodesExist = await Zipcode.find({
                    _id: { $in: updateData.zipcodes }
                }).session(session);
                
                if (zipcodesExist.length !== updateData.zipcodes.length) {
                    await session.abortTransaction();
                    session.endSession();
                    return res.status(404).json({
                        success: false,
                        message: 'One or more zipcodes not found'
                    });
                }
                
                updates.zipcodes = updateData.zipcodes;
            }
        }

        // Update other fields
        const fieldMappings = {
            bank_details: 'bank_details',
            documents: 'documents',
            tax_info: 'tax_info',
            permissions: 'permissions',
            commission: 'commission'
        };

        for (const [reqField, dbField] of Object.entries(fieldMappings)) {
            if (updateData[reqField] !== undefined) {
                if (dbField === 'commission') {
                    updates[dbField] = parseFloat(updateData[reqField]) || 0.00;
                } else {
                    updates[dbField] = {
                        ...(seller[dbField]?.toObject?.() || {}),
                        ...updateData[reqField]
                    };
                }
            }
        }

        // Update seller
        const updatedSeller = await Seller.findByIdAndUpdate(
            id,
            updates,
            { new: true, runValidators: true, session }
        )
        .populate('user_id', 'username email')
        .populate('category_ids', 'name')
        .populate('zipcodes', 'zipcode')
        .lean();

        await session.commitTransaction();
        session.endSession();

        res.status(200).json({
            success: true,
            message: 'Seller updated successfully',
            data: updatedSeller
        });

    } catch (error) {
        await session.abortTransaction();
        session.endSession();
        
        console.error('Error updating seller:', error);
        
        if (error.name === 'ValidationError') {
            const messages = Object.values(error.errors).map(err => err.message);
            return res.status(400).json({
                success: false,
                message: 'Validation failed',
                errors: messages
            });
        }
        
        res.status(500).json({
            success: false,
            message: 'Failed to update seller'
        });
    }
};

// 7. UPDATE - Update seller status (approve/reject/deactivate)
const updateSellerStatus = async (req, res) => {
    const session = await mongoose.startSession();
    session.startTransaction();
    
    try {
        const { id } = req.params;
        const { status, reason } = req.body;

        // Validate ID
        if (!mongoose.Types.ObjectId.isValid(id)) {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({
                success: false,
                message: 'Invalid Seller ID format'
            });
        }

        // Validate status
        const validStatuses = ['approved', 'not_approved', 'deactive', 'removed'];
        if (!status || !validStatuses.includes(status)) {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({
                success: false,
                message: `Invalid status. Valid statuses: ${validStatuses.join(', ')}`
            });
        }

        // Get seller
        const seller = await Seller.findById(id).session(session);
        if (!seller) {
            await session.abortTransaction();
            session.endSession();
            return res.status(404).json({
                success: false,
                message: 'Seller not found'
            });
        }

        // Don't allow changing to same status
        if (seller.status === status) {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({
                success: false,
                message: `Seller is already ${status}`
            });
        }

        // Store previous status
        const previousStatus = seller.status;

        // Update status
        seller.status = status;
        seller.status_history = seller.status_history || [];
        seller.status_history.push({
            from: previousStatus,
            to: status,
            changed_at: new Date(),
            reason: reason || 'No reason provided',
            changed_by: req.user?._id || 'system'
        });

        await seller.save({ session });

        // Send notification based on status change
        if (status === 'approved') {
            // Send approval notification
            console.log(`Seller ${seller._id} approved. Notifying user ${seller.user_id}`);

            // --- Referral Reward Logic ---
            await issueReferralReward(seller.user_id, session);
            // -----------------------------

        } else if (status === 'deactive' || status === 'removed') {
            // Send deactivation/removal notification
            console.log(`Seller ${seller._id} status changed to ${status}. Reason: ${reason}`);
        }

        await session.commitTransaction();
        session.endSession();

        res.status(200).json({
            success: true,
            message: `Seller status updated from ${previousStatus} to ${status}`,
            data: {
                seller_id: seller._id,
                store_name: seller.store_info.name,
                previous_status: previousStatus,
                new_status: seller.status,
                updated_at: seller.updatedAt
            }
        });

    } catch (error) {
        await session.abortTransaction();
        session.endSession();
        
        console.error('Error updating seller status:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to update seller status'
        });
    }
};

// 8. UPDATE - Update seller rating
const updateSellerRating = async (req, res) => {
    const session = await mongoose.startSession();
    session.startTransaction();
    
    try {
        const { id } = req.params;
        const { rating, review } = req.body;

        // Validate ID
        if (!mongoose.Types.ObjectId.isValid(id)) {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({
                success: false,
                message: 'Invalid Seller ID format'
            });
        }

        // Validate rating
        if (rating === undefined || rating < 0 || rating > 5) {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({
                success: false,
                message: 'Rating must be between 0 and 5'
            });
        }

        // Get seller
        const seller = await Seller.findById(id).session(session);
        if (!seller) {
            await session.abortTransaction();
            session.endSession();
            return res.status(404).json({
                success: false,
                message: 'Seller not found'
            });
        }

        // Calculate new average
        const currentTotal = seller.ratings.average * seller.ratings.count;
        const newCount = seller.ratings.count + 1;
        const newAverage = (currentTotal + rating) / newCount;

        // Update ratings
        seller.ratings = {
            average: parseFloat(newAverage.toFixed(2)),
            count: newCount
        };

        // Add review to history if provided
        if (review) {
            seller.review_history = seller.review_history || [];
            seller.review_history.push({
                rating,
                review: review.trim(),
                reviewed_at: new Date(),
                reviewer_id: req.user?._id || null
            });
        }

        await seller.save({ session });

        await session.commitTransaction();
        session.endSession();

        res.status(200).json({
            success: true,
            message: 'Seller rating updated successfully',
            data: {
                seller_id: seller._id,
                store_name: seller.store_info.name,
                ratings: seller.ratings,
                previous_average: currentTotal / seller.ratings.count
            }
        });

    } catch (error) {
        await session.abortTransaction();
        session.endSession();
        
        console.error('Error updating seller rating:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to update seller rating'
        });
    }
};

// 9. DELETE - Remove seller (soft delete)
const deleteSeller = async (req, res) => {
    const session = await mongoose.startSession();
    session.startTransaction();
    
    try {
        const { id } = req.params;
        const { reason, permanent = false } = req.body;

        // Validate ID
        if (!mongoose.Types.ObjectId.isValid(id)) {
            await session.abortTransaction();
            session.endSession();
            return res.status(400).json({
                success: false,
                message: 'Invalid Seller ID format'
            });
        }

        // Get seller
        const seller = await Seller.findById(id).session(session);
        if (!seller) {
            await session.abortTransaction();
            session.endSession();
            return res.status(404).json({
                success: false,
                message: 'Seller not found'
            });
        }

        if (permanent) {
            // Permanent deletion (admin only)
            await Seller.findByIdAndDelete(id, { session });
            
            await session.commitTransaction();
            session.endSession();

            res.status(200).json({
                success: true,
                message: 'Seller permanently deleted',
                data: {
                    seller_id: id,
                    store_name: seller.store_info.name,
                    deleted_at: new Date()
                }
            });
        } else {
            // Soft delete (change status to removed)
            seller.status = 'removed';
            seller.removal_info = {
                removed_at: new Date(),
                removed_by: req.user?._id || null,
                reason: reason || 'No reason provided',
                permanent: false
            };

            await seller.save({ session });

            await session.commitTransaction();
            session.endSession();

            res.status(200).json({
                success: true,
                message: 'Seller marked as removed',
                data: {
                    seller_id: seller._id,
                    store_name: seller.store_info.name,
                    status: seller.status,
                    removed_at: seller.removal_info.removed_at
                }
            });
        }

    } catch (error) {
        await session.abortTransaction();
        session.endSession();
        
        console.error('Error removing seller:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to remove seller'
        });
    }
};

// 10. UTILITY - Check seller serviceability by zipcode
const checkSellerServiceability = async (req, res) => {
    try {
        const { seller_id } = req.params;
        const { zipcode } = req.query;

        if (!zipcode) {
            return res.status(400).json({
                success: false,
                message: 'Zipcode is required'
            });
        }

        // Validate seller ID
        if (!mongoose.Types.ObjectId.isValid(seller_id)) {
            return res.status(400).json({
                success: false,
                message: 'Invalid Seller ID format'
            });
        }

        // Get seller
        const seller = await Seller.findById(seller_id)
            .populate('zipcodes', 'zipcode')
            .select('status zipcodes store_info.name')
            .lean();

        if (!seller) {
            return res.status(404).json({
                success: false,
                message: 'Seller not found'
            });
        }

        // Check if seller is approved
        if (seller.status !== 'approved') {
            return res.status(200).json({
                success: true,
                message: 'Seller is not approved for operations',
                data: {
                    serviceable: false,
                    reason: 'Seller not approved',
                    seller_status: seller.status
                }
            });
        }

        // Find zipcode in seller's serviceable areas
        const zipcodeDoc = await Zipcode.findOne({ zipcode });
        if (!zipcodeDoc) {
            return res.status(200).json({
                success: true,
                message: 'Zipcode not found in system',
                data: {
                    serviceable: false,
                    reason: 'Zipcode not in system'
                }
            });
        }

        const isServiceable = seller.zipcodes.some(z => 
            z._id.toString() === zipcodeDoc._id.toString()
        );

        res.status(200).json({
            success: true,
            message: isServiceable ? 'Seller services this area' : 'Seller does not service this area',
            data: {
                serviceable: isServiceable,
                seller_name: seller.store_info.name,
                zipcode,
                serviceable_areas: seller.zipcodes.map(z => z.zipcode)
            }
        });

    } catch (error) {
        console.error('Error checking serviceability:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to check serviceability'
        });
    }
};

// 11. ANALYTICS - Get seller statistics
const getSellerStatistics = async (req, res) => {
    try {
        const { seller_id } = req.params;

        if (!mongoose.Types.ObjectId.isValid(seller_id)) {
            return res.status(400).json({
                success: false,
                message: 'Invalid Seller ID format'
            });
        }

        // Get seller basic info
        const seller = await Seller.findById(seller_id)
            .populate('user_id', 'username email')
            .populate('category_ids', 'name')
            .select('store_info ratings status commission createdAt')
            .lean();

        if (!seller) {
            return res.status(404).json({
                success: false,
                message: 'Seller not found'
            });
        }

        // You would typically fetch from OrderItem model for these stats
        const statistics = {
            // Placeholder - implement based on your OrderItem model
            total_orders: 0,
            total_revenue: 0,
            pending_orders: 0,
            completed_orders: 0,
            average_order_value: 0,
            total_customers: 0,
            this_month: {
                orders: 0,
                revenue: 0,
                new_customers: 0
            }
        };

        res.status(200).json({
            success: true,
            message: 'Seller statistics retrieved',
            data: {
                seller: {
                    id: seller._id,
                    store_name: seller.store_info.name,
                    status: seller.status,
                    rating: seller.ratings.average,
                    rating_count: seller.ratings.count,
                    commission_rate: seller.commission,
                    joined_date: seller.createdAt
                },
                statistics,
                performance: {
                    rating_stars: '⭐'.repeat(Math.floor(seller.ratings.average)) + 
                                (seller.ratings.average % 1 >= 0.5 ? '½' : '')
                }
            }
        });

    } catch (error) {
        console.error('Error fetching seller statistics:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to fetch seller statistics'
        });
    }
};

module.exports = {
    createSeller,
    getAllSellers,
    getSellerById,
    getSellerByUserId,
    getSellerBySlug,
    updateSeller,
    updateSellerStatus,
    updateSellerRating,
    deleteSeller,
    checkSellerServiceability,
    getSellerStatistics
};